---

- name: restart carbon-cache
  service: name=carbon-cache state=restarted

- name: restart uwsgi
  service: name=uwsgi state=restarted

- name: restart nginx
  service: name=nginx state=restarted